### ISSUE TITLE
Password schema is duplicated

### ISSUE THREAD

**Issue by sparse91** [sius/pencil#2]
Hello. I try to encoding password with SSHA512PasswordEncoder with this code
```
private static PasswordEncoder createDelegatingPasswordEncoder() {
    String encodingId = "SSHA512";
    var encoders = new HashMap<String, PasswordEncoder>();
    encoders.put(encodingId, new SSHA512PasswordEncoder());
    encoders.put("bcrypt", new BCryptPasswordEncoder());
    return new DelegatingPasswordEncoder(encodingId, encoders);
}
```
Schema is duplicated in the result:
![image](https://user-images.githubusercontent.com/26763315/122892627-cb85e800-d35a-11eb-9c6e-ee8cabb6e990.png)

What is the reason?

**Comment by sparse91** [comment]
I created a PasswordEncoder directly with SSHA512PasswordEncoder and problem solved for me. But how can I use a DelegatingPasswordEncoder with SSHA512PasswordEncoder?

```
private static final PasswordEncoder passwordEncoder = new SSHA512PasswordEncoder();
```

**Comment by sius** [comment]
You dont't have to create your own DelegatingPasswordEncoder.
Simply use the provided DelegatingPasswordEncoder that supports the standard Spring PasswordEncoders

```java
@Autowired
private PasswordEncoder passwordEncoder;
```

But you can disable the provided DelegatingPasswordEncoder with the application property  
`liquer.pencil.enabled: false`

To provide your own Delegation PasswordEncoder use the following Constructor

```java
encoders.put(encodingId, new SSHA512PasswordEncoder("", 8));
```

**Comment by sius** [comment]
The Standard Constructor prepends the Algorithm Identifier
