### ISSUE TITLE
Ldap SSHA512 passwords does not match with SSHA512PasswordEncoder

### ISSUE THREAD

**Issue by sparse91** [sius/pencil#3]
Hello
I have a Ldap Server with SSHA512 encoded passwords. I'm trying to move Ldap data to a SQL database. For passwordEncoder I'm using SSHA512PasswordEncoder but most of password does not match. What could be the problem?
The code of Ldap is in this link: https://github.com/389ds/389-ds-base/blob/389-ds-base-1.3.10/ldap/servers/plugins/pwdstorage/ssha_pwd.c
Can you take a look at this?

**Comment by sparse91** [comment]
Different hashes for this password '!newPass1234' with same salt:
Ldap:
{SSHA512}Fr4BnihVzVb0tqoknqjM1nP6K2fQ1deINvbqXmo8h8362k6Gmh7Av+KP68g9Llua6meqXVIXMP9CZvDd4sy1VlqZBQzLVgqF

SSHA512PasswordEncoder:
{SSHA512}MdMnk2tj2NuijXkjfTzFQicbxG-7SQ9Etzxqso6TzlorFm5g5kB_KKQZg694gQEnJvdPgkKrg1wxCzqXcQqZ_lqZBQzLVgqF

**Comment by sius** [comment]
@sparse91 
The LDAP server password hash was generated using an ISO_8859_1 charset.

The hashes generated with Pencil use UTF8 charset. Unfortunately, the charset cannot be parameterized at the moment.
I will take care of an update

**Comment by sius** [comment]
@sparse91

There is a new version that should solve your problem

```xml
<dependency>
  <groupId>io.liquer.pencil</groupId>
  <artifactId>pencil-spring-boot-starter</artifactId>
  <version>1.1.0</version>
</dependency>
```
Please see the following usage examples.
They show the usage of the DelegatingPasswordEncoder configuration through Spring Boot Properties:
-  [Issue7iso8859_1AutoConfigTest.java](https://github.com/sius/pencil/blob/master/pencil-tests/src/test/java/io/liquer/pencil/issue/Issue7iso8859_1AutoConfigTest.java)
- [Issue7ufSafeAutoConfigTest.java](https://github.com/sius/pencil/blob/master/pencil-tests/src/test/java/io/liquer/pencil/issue/Issue7ufSafeAutoConfigTest.java)
  
and the direct usage of the `SSHA512PasswordEncoder`:
- [Issue7Test.java](https://github.com/sius/pencil/blob/master/pencil-tests/src/test/java/io/liquer/pencil/issue/Issue7Test.java)

The `underscore` and the `hyphen` in the second hash show that you are using ufSafe (URL and file safe) base64 encoding. Please do not use it in your specific use case. You only have to provide the ISO_8859_1 Charset.

You can find more Informations in the [README](https://github.com/sius/pencil#readme)

**Comment by sparse91** [comment]
Thank you for your support and work.
